# Generated by Django 5.0.7 on 2025-01-30 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bananas_coctails', '0006_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cocteles',
            field=models.JSONField(),
        ),
    ]
